apiVersion: v1
kind: Service
metadata:
  name: gamenetpanelservice
spec:
  selector:
    app: gamenetpanelpod
  # type: NodePort # For NodePort Service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 4000 # App will be accessable on the port 80 of External IP
      targetPort: 80
      # nodePort: 30001 # App will be accessable from http://Master_Node_IP:300001 for NodePort Service
